# Local development override - adds live code reloading for backend
services:
  open-router-pg-local:
    build:
      context: .
      dockerfile: Dockerfile.postgres
      args:
        - BUILDKIT_INLINE_CACHE=1
    profiles:
      - local-postgres
      - local-dev
    container_name: open-router-pg-local
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9094:9094"
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
      db-migrator-postgres:
        condition: service_completed_successfully
    volumes:
      - ./config/docker-configuration.toml:/local/config/development.toml
    networks:
      - open-router-network
    environment:
      - GROOVY_RUNNER_HOST=host.docker.internal:8085
