use crate::error::ApiError;
use serde::{Deserialize, Serialize};
use std::hash::Hash;
use std::string::String;
#[derive(Debug, PartialEq, Eq, Hash, Serialize, Deserialize, Clone, Copy)]
pub enum CountryISO {
    AFG,
    AIA,
    ALA,
    ALB,
    AND,
    AGO,
    ARE,
    ARG,
    ARM,
    ASM,
    ATG,
    AUS,
    AUT,
    AZE,
    BDI,
    BEL,
    BEN,
    BFA,
    BGD,
    BGR,
    BHR,
    BHS,
    BIH,
    BLR,
    BLZ,
    BOL,
    BRA,
    BRB,
    BRN,
    BTN,
    BWA,
    CAF,
    CAN,
    CHE,
    CHL,
    CHN,
    CMR,
    COD,
    COG,
    COL,
    COM,
    CPV,
    CRI,
    CUB,
    CYP,
    CZE,
    DEU,
    DJI,
    DMA,
    DNK,
    DOM,
    DZA,
    ECU,
    EGY,
    ERI,
    ESP,
    EST,
    ETH,
    FIN,
    FJI,
    FRA,
    FSM,
    GAB,
    GBR,
    GEO,
    GHA,
    GIN,
    GMB,
    GNB,
    GNQ,
    GRC,
    GRD,
    GTM,
    GUY,
    HKG,
    HND,
    HRV,
    HTI,
    HUN,
    IDN,
    IND,
    IRL,
    IRN,
    IRQ,
    ISL,
    ISR,
    ITA,
    JAM,
    JOR,
    JPN,
    KAZ,
    KEN,
    KGZ,
    KHM,
    KIR,
    KNA,
    KOR,
    KWT,
    LAO,
    LBN,
    LBR,
    LBY,
    LCA,
    LIE,
    LKA,
    LSO,
    LTU,
    LUX,
    LVA,
    MAR,
    MCO,
    MDA,
    MDG,
    MDV,
    MEX,
    MHL,
    MKD,
    MLI,
    MLT,
    MMR,
    MNG,
    MNE,
    MOZ,
    MRT,
    MUS,
    MWI,
    MYS,
    NAM,
    NER,
    NGA,
    NIC,
    NLD,
    NOR,
    NPL,
    NRU,
    NZL,
    OMN,
    PAK,
    PAN,
    PER,
    PHL,
    PLW,
    PNG,
    POL,
    PRT,
    PRY,
    QAT,
    ROU,
    RUS,
    RWA,
    SAU,
    SDN,
    SEN,
    SGP,
    SLB,
    SLE,
    SLV,
    SMR,
    SOM,
    SRB,
    SSD,
    STP,
    SUR,
    SVK,
    SVN,
    SWE,
    SWZ,
    SYC,
    SYR,
    TCD,
    TGO,
    THA,
    TJK,
    TKM,
    TLS,
    TON,
    TTO,
    TUN,
    TUR,
    TUV,
    TZA,
    UGA,
    UKR,
    URY,
    USA,
    UZB,
    VEN,
    VCT,
    VNM,
    VUT,
    WSM,
    YEM,
    ZAF,
    ZMB,
    ZWE,
}

pub fn country_iso_to_text(country_iso: CountryISO) -> String {
    format!("{:?}", country_iso)
}

pub fn text_db_to_country_iso(text: &str) -> Result<CountryISO, ApiError> {
    match text {
        "AFG" => Ok(CountryISO::AFG),
        "AIA" => Ok(CountryISO::AIA),
        "ALA" => Ok(CountryISO::ALA),
        "ALB" => Ok(CountryISO::ALB),
        "AND" => Ok(CountryISO::AND),
        "AGO" => Ok(CountryISO::AGO),
        "ARE" => Ok(CountryISO::ARE),
        "ARG" => Ok(CountryISO::ARG),
        "ARM" => Ok(CountryISO::ARM),
        "ASM" => Ok(CountryISO::ASM),
        "ATG" => Ok(CountryISO::ATG),
        "AUS" => Ok(CountryISO::AUS),
        "AUT" => Ok(CountryISO::AUT),
        "AZE" => Ok(CountryISO::AZE),
        "BDI" => Ok(CountryISO::BDI),
        "BEL" => Ok(CountryISO::BEL),
        "BEN" => Ok(CountryISO::BEN),
        "BFA" => Ok(CountryISO::BFA),
        "BGD" => Ok(CountryISO::BGD),
        "BGR" => Ok(CountryISO::BGR),
        "BHR" => Ok(CountryISO::BHR),
        "BHS" => Ok(CountryISO::BHS),
        "BIH" => Ok(CountryISO::BIH),
        "BLR" => Ok(CountryISO::BLR),
        "BLZ" => Ok(CountryISO::BLZ),
        "BOL" => Ok(CountryISO::BOL),
        "BRA" => Ok(CountryISO::BRA),
        "BRB" => Ok(CountryISO::BRB),
        "BRN" => Ok(CountryISO::BRN),
        "BTN" => Ok(CountryISO::BTN),
        "BWA" => Ok(CountryISO::BWA),
        "CAF" => Ok(CountryISO::CAF),
        "CAN" => Ok(CountryISO::CAN),
        "CHE" => Ok(CountryISO::CHE),
        "CHL" => Ok(CountryISO::CHL),
        "CHN" => Ok(CountryISO::CHN),
        "CMR" => Ok(CountryISO::CMR),
        "COD" => Ok(CountryISO::COD),
        "COG" => Ok(CountryISO::COG),
        "COL" => Ok(CountryISO::COL),
        "COM" => Ok(CountryISO::COM),
        "CPV" => Ok(CountryISO::CPV),
        "CRI" => Ok(CountryISO::CRI),
        "CUB" => Ok(CountryISO::CUB),
        "CYP" => Ok(CountryISO::CYP),
        "CZE" => Ok(CountryISO::CZE),
        "DEU" => Ok(CountryISO::DEU),
        "DJI" => Ok(CountryISO::DJI),
        "DMA" => Ok(CountryISO::DMA),
        "DNK" => Ok(CountryISO::DNK),
        "DOM" => Ok(CountryISO::DOM),
        "DZA" => Ok(CountryISO::DZA),
        "ECU" => Ok(CountryISO::ECU),
        "EGY" => Ok(CountryISO::EGY),
        "ERI" => Ok(CountryISO::ERI),
        "ESP" => Ok(CountryISO::ESP),
        "EST" => Ok(CountryISO::EST),
        "ETH" => Ok(CountryISO::ETH),
        "FIN" => Ok(CountryISO::FIN),
        "FJI" => Ok(CountryISO::FJI),
        "FRA" => Ok(CountryISO::FRA),
        "FSM" => Ok(CountryISO::FSM),
        "GAB" => Ok(CountryISO::GAB),
        "GBR" => Ok(CountryISO::GBR),
        "GEO" => Ok(CountryISO::GEO),
        "GHA" => Ok(CountryISO::GHA),
        "GIN" => Ok(CountryISO::GIN),
        "GMB" => Ok(CountryISO::GMB),
        "GNB" => Ok(CountryISO::GNB),
        "GNQ" => Ok(CountryISO::GNQ),
        "GRC" => Ok(CountryISO::GRC),
        "GRD" => Ok(CountryISO::GRD),
        "GTM" => Ok(CountryISO::GTM),
        "GUY" => Ok(CountryISO::GUY),
        "HKG" => Ok(CountryISO::HKG),
        "HND" => Ok(CountryISO::HND),
        "HRV" => Ok(CountryISO::HRV),
        "HTI" => Ok(CountryISO::HTI),
        "HUN" => Ok(CountryISO::HUN),
        "IDN" => Ok(CountryISO::IDN),
        "IND" => Ok(CountryISO::IND),
        "IRL" => Ok(CountryISO::IRL),
        "IRN" => Ok(CountryISO::IRN),
        "IRQ" => Ok(CountryISO::IRQ),
        "ISL" => Ok(CountryISO::ISL),
        "ISR" => Ok(CountryISO::ISR),
        "ITA" => Ok(CountryISO::ITA),
        "JAM" => Ok(CountryISO::JAM),
        "JOR" => Ok(CountryISO::JOR),
        "JPN" => Ok(CountryISO::JPN),
        "KAZ" => Ok(CountryISO::KAZ),
        "KEN" => Ok(CountryISO::KEN),
        "KGZ" => Ok(CountryISO::KGZ),
        "KHM" => Ok(CountryISO::KHM),
        "KIR" => Ok(CountryISO::KIR),
        "KNA" => Ok(CountryISO::KNA),
        "KOR" => Ok(CountryISO::KOR),
        "KWT" => Ok(CountryISO::KWT),
        "LAO" => Ok(CountryISO::LAO),
        "LBN" => Ok(CountryISO::LBN),
        "LBR" => Ok(CountryISO::LBR),
        "LBY" => Ok(CountryISO::LBY),
        "LCA" => Ok(CountryISO::LCA),
        "LIE" => Ok(CountryISO::LIE),
        "LKA" => Ok(CountryISO::LKA),
        "LSO" => Ok(CountryISO::LSO),
        "LTU" => Ok(CountryISO::LTU),
        "LUX" => Ok(CountryISO::LUX),
        "LVA" => Ok(CountryISO::LVA),
        "MAR" => Ok(CountryISO::MAR),
        "MCO" => Ok(CountryISO::MCO),
        "MDA" => Ok(CountryISO::MDA),
        "MDG" => Ok(CountryISO::MDG),
        "MDV" => Ok(CountryISO::MDV),
        "MEX" => Ok(CountryISO::MEX),
        "MHL" => Ok(CountryISO::MHL),
        "MKD" => Ok(CountryISO::MKD),
        "MLI" => Ok(CountryISO::MLI),
        "MLT" => Ok(CountryISO::MLT),
        "MMR" => Ok(CountryISO::MMR),
        "MNG" => Ok(CountryISO::MNG),
        "MNE" => Ok(CountryISO::MNE),
        "MOZ" => Ok(CountryISO::MOZ),
        "MRT" => Ok(CountryISO::MRT),
        "MUS" => Ok(CountryISO::MUS),
        "MWI" => Ok(CountryISO::MWI),
        "MYS" => Ok(CountryISO::MYS),
        "NAM" => Ok(CountryISO::NAM),
        "NER" => Ok(CountryISO::NER),
        "NGA" => Ok(CountryISO::NGA),
        "NIC" => Ok(CountryISO::NIC),
        "NLD" => Ok(CountryISO::NLD),
        "NOR" => Ok(CountryISO::NOR),
        "NPL" => Ok(CountryISO::NPL),
        "NRU" => Ok(CountryISO::NRU),
        "NZL" => Ok(CountryISO::NZL),
        "OMN" => Ok(CountryISO::OMN),
        "PAK" => Ok(CountryISO::PAK),
        "PAN" => Ok(CountryISO::PAN),
        "PER" => Ok(CountryISO::PER),
        "PHL" => Ok(CountryISO::PHL),
        "PLW" => Ok(CountryISO::PLW),
        "PNG" => Ok(CountryISO::PNG),
        "POL" => Ok(CountryISO::POL),
        "PRT" => Ok(CountryISO::PRT),
        "PRY" => Ok(CountryISO::PRY),
        "QAT" => Ok(CountryISO::QAT),
        "ROU" => Ok(CountryISO::ROU),
        "RUS" => Ok(CountryISO::RUS),
        "RWA" => Ok(CountryISO::RWA),
        "SAU" => Ok(CountryISO::SAU),
        "SDN" => Ok(CountryISO::SDN),
        "SEN" => Ok(CountryISO::SEN),
        "SGP" => Ok(CountryISO::SGP),
        "SLB" => Ok(CountryISO::SLB),
        "SLE" => Ok(CountryISO::SLE),
        "SLV" => Ok(CountryISO::SLV),
        "SMR" => Ok(CountryISO::SMR),
        "SOM" => Ok(CountryISO::SOM),
        "SRB" => Ok(CountryISO::SRB),
        "SSD" => Ok(CountryISO::SSD),
        "STP" => Ok(CountryISO::STP),
        "SUR" => Ok(CountryISO::SUR),
        "SVK" => Ok(CountryISO::SVK),
        "SVN" => Ok(CountryISO::SVN),
        "SWE" => Ok(CountryISO::SWE),
        "SWZ" => Ok(CountryISO::SWZ),
        "SYC" => Ok(CountryISO::SYC),
        "SYR" => Ok(CountryISO::SYR),
        "TCD" => Ok(CountryISO::TCD),
        "TGO" => Ok(CountryISO::TGO),
        "THA" => Ok(CountryISO::THA),
        "TJK" => Ok(CountryISO::TJK),
        "TKM" => Ok(CountryISO::TKM),
        "TLS" => Ok(CountryISO::TLS),
        "TON" => Ok(CountryISO::TON),
        "TTO" => Ok(CountryISO::TTO),
        "TUN" => Ok(CountryISO::TUN),
        "TUR" => Ok(CountryISO::TUR),
        "TUV" => Ok(CountryISO::TUV),
        "TZA" => Ok(CountryISO::TZA),
        "UGA" => Ok(CountryISO::UGA),
        "UKR" => Ok(CountryISO::UKR),
        "URY" => Ok(CountryISO::URY),
        "USA" => Ok(CountryISO::USA),
        "UZB" => Ok(CountryISO::UZB),
        "VEN" => Ok(CountryISO::VEN),
        "VCT" => Ok(CountryISO::VCT),
        "VNM" => Ok(CountryISO::VNM),
        "VUT" => Ok(CountryISO::VUT),
        "WSM" => Ok(CountryISO::WSM),
        "YEM" => Ok(CountryISO::YEM),
        "ZAF" => Ok(CountryISO::ZAF),
        "ZMB" => Ok(CountryISO::ZMB),
        "ZWE" => Ok(CountryISO::ZWE),
        _ => Err(ApiError::ParsingError("Invalid Country ISO")),
    }
}


#[derive(Debug, PartialEq, Eq, Hash, Serialize, Deserialize, Clone, strum::Display, Copy)]
pub enum CountryISO2 {
    AD,
    AE,
    AF,
    AG,
    AI,
    AL,
    AM,
    AO,
    AQ,
    AR,
    AS,
    AT,
    AU,
    AW,
    AX,
    AZ,
    BA,
    BB,
    BD,
    BE,
    BF,
    BG,
    BH,
    BI,
    BJ,
    BL,
    BM,
    BN,
    BO,
    BQ,
    BR,
    BS,
    BT,
    BV,
    BW,
    BY,
    BZ,
    CA,
    CC,
    CD,
    CF,
    CG,
    CH,
    CI,
    CK,
    CL,
    CM,
    CN,
    CO,
    CR,
    CU,
    CV,
    CW,
    CX,
    CY,
    CZ,
    DE,
    DJ,
    DK,
    DM,
    DO,
    DZ,
    EC,
    EE,
    EH,
    EG,
    ER,
    ES,
    ET,
    FI,
    FJ,
    FK,
    FM,
    FO,
    FR,
    GA,
    GB,
    GD,
    GE,
    GF,
    GG,
    GH,
    GI,
    GL,
    GM,
    GN,
    GP,
    GQ,
    GR,
    GS,
    GT,
    GU,
    GW,
    GY,
    HK,
    HM,
    HN,
    HR,
    HT,
    HU,
    ID,
    IE,
    IL,
    IM,
    IN,
    IO,
    IQ,
    IR,
    IS,
    IT,
    JE,
    JM,
    JO,
    JP,
    KE,
    KG,
    KH,
    KI,
    KM,
    KN,
    KP,
    KR,
    KW,
    KY,
    KZ,
    LA,
    LB,
    LC,
    LI,
    LK,
    LR,
    LS,
    LT,
    LU,
    LV,
    LY,
    MA,
    MC,
    MD,
    ME,
    MF,
    MG,
    MH,
    MK,
    ML,
    MM,
    MN,
    MO,
    MP,
    MQ,
    MR,
    MS,
    MT,
    MU,
    MV,
    MW,
    MX,
    MY,
    MZ,
    NA,
    NC,
    NE,
    NF,
    NG,
    NI,
    NL,
    NO,
    NP,
    NR,
    NU,
    NZ,
    OM,
    PA,
    PE,
    PF,
    PG,
    PH,
    PK,
    PL,
    PM,
    PN,
    PR,
    PS,
    PT,
    PW,
    PY,
    QA,
    RE,
    RO,
    RS,
    RU,
    RW,
    SA,
    SB,
    SC,
    SD,
    SE,
    SG,
    SH,
    SI,
    SJ,
    SK,
    SL,
    SM,
    SN,
    SO,
    SR,
    SS,
    ST,
    SV,
    SX,
    SY,
    SZ,
    TC,
    TD,
    TF,
    TG,
    TH,
    TJ,
    TK,
    TL,
    TM,
    TN,
    TO,
    TR,
    TT,
    TV,
    TW,
    TZ,
    UA,
    UG,
    UM,
    US,
    UY,
    UZ,
    VA,
    VC,
    VE,
    VG,
    VI,
    VN,
    VU,
    WF,
    WS,
    YE,
    YT,
    ZA,
    ZM,
    ZW,
}

impl CountryISO2 {
    pub fn text_to_country(text: &str) -> Result<Self, ApiError> {
        match text {
            "AD" => Ok(CountryISO2::AD),
            "AE" => Ok(CountryISO2::AE),
            "AF" => Ok(CountryISO2::AF),
            "AG" => Ok(CountryISO2::AG),
            "AI" => Ok(CountryISO2::AI),
            "AL" => Ok(CountryISO2::AL),
            "AM" => Ok(CountryISO2::AM),
            "AO" => Ok(CountryISO2::AO),
            "AQ" => Ok(CountryISO2::AQ),
            "AR" => Ok(CountryISO2::AR),
            "AS" => Ok(CountryISO2::AS),
            "AT" => Ok(CountryISO2::AT),
            "AU" => Ok(CountryISO2::AU),
            "AW" => Ok(CountryISO2::AW),
            "AX" => Ok(CountryISO2::AX),
            "AZ" => Ok(CountryISO2::AZ),
            "BA" => Ok(CountryISO2::BA),
            "BB" => Ok(CountryISO2::BB),
            "BD" => Ok(CountryISO2::BD),
            "BE" => Ok(CountryISO2::BE),
            "BF" => Ok(CountryISO2::BF),
            "BG" => Ok(CountryISO2::BG),
            "BH" => Ok(CountryISO2::BH),
            "BI" => Ok(CountryISO2::BI),
            "BJ" => Ok(CountryISO2::BJ),
            "BL" => Ok(CountryISO2::BL),
            "BM" => Ok(CountryISO2::BM),
            "BN" => Ok(CountryISO2::BN),
            "BO" => Ok(CountryISO2::BO),
            "BQ" => Ok(CountryISO2::BQ),
            "BR" => Ok(CountryISO2::BR),
            "BS" => Ok(CountryISO2::BS),
            "BT" => Ok(CountryISO2::BT),
            "BV" => Ok(CountryISO2::BV),
            "BW" => Ok(CountryISO2::BW),
            "BY" => Ok(CountryISO2::BY),
            "BZ" => Ok(CountryISO2::BZ),
            "CA" => Ok(CountryISO2::CA),
            "CC" => Ok(CountryISO2::CC),
            "CD" => Ok(CountryISO2::CD),
            "CF" => Ok(CountryISO2::CF),
            "CG" => Ok(CountryISO2::CG),
            "CH" => Ok(CountryISO2::CH),
            "CI" => Ok(CountryISO2::CI),
            "CK" => Ok(CountryISO2::CK),
            "CL" => Ok(CountryISO2::CL),
            "CM" => Ok(CountryISO2::CM),
            "CN" => Ok(CountryISO2::CN),
            "CO" => Ok(CountryISO2::CO),
            "CR" => Ok(CountryISO2::CR),
            "CU" => Ok(CountryISO2::CU),
            "CV" => Ok(CountryISO2::CV),
            "CW" => Ok(CountryISO2::CW),
            "CX" => Ok(CountryISO2::CX),
            "CY" => Ok(CountryISO2::CY),
            "CZ" => Ok(CountryISO2::CZ),
            "DE" => Ok(CountryISO2::DE),
            "DJ" => Ok(CountryISO2::DJ),
            "DK" => Ok(CountryISO2::DK),
            "DM" => Ok(CountryISO2::DM),
            "DO" => Ok(CountryISO2::DO),
            "DZ" => Ok(CountryISO2::DZ),
            "EC" => Ok(CountryISO2::EC),
            "EE" => Ok(CountryISO2::EE),
            "EH" => Ok(CountryISO2::EH),
            "EG" => Ok(CountryISO2::EG),
            "ER" => Ok(CountryISO2::ER),
            "ES" => Ok(CountryISO2::ES),
            "ET" => Ok(CountryISO2::ET),
            "FI" => Ok(CountryISO2::FI),
            "FJ" => Ok(CountryISO2::FJ),
            "FK" => Ok(CountryISO2::FK),
            "FM" => Ok(CountryISO2::FM),
            "FO" => Ok(CountryISO2::FO),
            "FR" => Ok(CountryISO2::FR),
            "GA" => Ok(CountryISO2::GA),
            "GB" => Ok(CountryISO2::GB),
            "GD" => Ok(CountryISO2::GD),
            "GE" => Ok(CountryISO2::GE),
            "GF" => Ok(CountryISO2::GF),
            "GG" => Ok(CountryISO2::GG),
            "GH" => Ok(CountryISO2::GH),
            "GI" => Ok(CountryISO2::GI),
            "GL" => Ok(CountryISO2::GL),
            "GM" => Ok(CountryISO2::GM),
            "GN" => Ok(CountryISO2::GN),
            "GP" => Ok(CountryISO2::GP),
            "GQ" => Ok(CountryISO2::GQ),
            "GR" => Ok(CountryISO2::GR),
            "GS" => Ok(CountryISO2::GS),
            "GT" => Ok(CountryISO2::GT),
            "GU" => Ok(CountryISO2::GU),
            "GW" => Ok(CountryISO2::GW),
            "GY" => Ok(CountryISO2::GY),
            "HK" => Ok(CountryISO2::HK),
            "HM" => Ok(CountryISO2::HM),
            "HN" => Ok(CountryISO2::HN),
            "HR" => Ok(CountryISO2::HR),
            "HT" => Ok(CountryISO2::HT),
            "HU" => Ok(CountryISO2::HU),
            "ID" => Ok(CountryISO2::ID),
            "IE" => Ok(CountryISO2::IE),
            "IL" => Ok(CountryISO2::IL),
            "IM" => Ok(CountryISO2::IM),
            "IN" => Ok(CountryISO2::IN),
            "IO" => Ok(CountryISO2::IO),
            "IQ" => Ok(CountryISO2::IQ),
            "IR" => Ok(CountryISO2::IR),
            "IS" => Ok(CountryISO2::IS),
            "IT" => Ok(CountryISO2::IT),
            "JE" => Ok(CountryISO2::JE),
            "JM" => Ok(CountryISO2::JM),
            "JO" => Ok(CountryISO2::JO),
            "JP" => Ok(CountryISO2::JP),
            "KE" => Ok(CountryISO2::KE),
            "KG" => Ok(CountryISO2::KG),
            "KH" => Ok(CountryISO2::KH),
            "KI" => Ok(CountryISO2::KI),
            "KM" => Ok(CountryISO2::KM),
            "KN" => Ok(CountryISO2::KN),
            "KP" => Ok(CountryISO2::KP),
            "KR" => Ok(CountryISO2::KR),
            "KW" => Ok(CountryISO2::KW),
            "KY" => Ok(CountryISO2::KY),
            "KZ" => Ok(CountryISO2::KZ),
            "LA" => Ok(CountryISO2::LA),
            "LB" => Ok(CountryISO2::LB),
            "LC" => Ok(CountryISO2::LC),
            "LI" => Ok(CountryISO2::LI),
            "LK" => Ok(CountryISO2::LK),
            "LR" => Ok(CountryISO2::LR),
            "LS" => Ok(CountryISO2::LS),
            "LT" => Ok(CountryISO2::LT),
            "LU" => Ok(CountryISO2::LU),
            "LV" => Ok(CountryISO2::LV),
            "LY" => Ok(CountryISO2::LY),
            "MA" => Ok(CountryISO2::MA),
            "MC" => Ok(CountryISO2::MC),
            "MD" => Ok(CountryISO2::MD),
            "ME" => Ok(CountryISO2::ME),
            "MF" => Ok(CountryISO2::MF),
            "MG" => Ok(CountryISO2::MG),
            "MH" => Ok(CountryISO2::MH),
            "MK" => Ok(CountryISO2::MK),
            "ML" => Ok(CountryISO2::ML),
            "MM" => Ok(CountryISO2::MM),
            "MN" => Ok(CountryISO2::MN),
            "MO" => Ok(CountryISO2::MO),
            "MP" => Ok(CountryISO2::MP),
            "MQ" => Ok(CountryISO2::MQ),
            "MR" => Ok(CountryISO2::MR),
            "MS" => Ok(CountryISO2::MS),
            "MT" => Ok(CountryISO2::MT),
            "MU" => Ok(CountryISO2::MU),
            "MV" => Ok(CountryISO2::MV),
            "MW" => Ok(CountryISO2::MW),
            "MX" => Ok(CountryISO2::MX),
            "MY" => Ok(CountryISO2::MY),
            "MZ" => Ok(CountryISO2::MZ),
            "NA" => Ok(CountryISO2::NA),
            "NC" => Ok(CountryISO2::NC),
            "NE" => Ok(CountryISO2::NE),
            "NF" => Ok(CountryISO2::NF),
            "NG" => Ok(CountryISO2::NG),
            "NI" => Ok(CountryISO2::NI),
            "NL" => Ok(CountryISO2::NL),
            "NO" => Ok(CountryISO2::NO),
            "NP" => Ok(CountryISO2::NP),
            "NR" => Ok(CountryISO2::NR),
            "NU" => Ok(CountryISO2::NU),
            "NZ" => Ok(CountryISO2::NZ),
            "OM" => Ok(CountryISO2::OM),
            "PA" => Ok(CountryISO2::PA),
            "PE" => Ok(CountryISO2::PE),
            "PF" => Ok(CountryISO2::PF),
            "PG" => Ok(CountryISO2::PG),
            "PH" => Ok(CountryISO2::PH),
            "PK" => Ok(CountryISO2::PK),
            "PL" => Ok(CountryISO2::PL),
            "PM" => Ok(CountryISO2::PM),
            "PN" => Ok(CountryISO2::PN),
            "PR" => Ok(CountryISO2::PR),
            "PS" => Ok(CountryISO2::PS),
            "PT" => Ok(CountryISO2::PT),
            "PW" => Ok(CountryISO2::PW),
            "PY" => Ok(CountryISO2::PY),
            "QA" => Ok(CountryISO2::QA),
            "RE" => Ok(CountryISO2::RE),
            "RO" => Ok(CountryISO2::RO),
            "RS" => Ok(CountryISO2::RS),
            "RU" => Ok(CountryISO2::RU),
            "RW" => Ok(CountryISO2::RW),
            "SA" => Ok(CountryISO2::SA),
            "SB" => Ok(CountryISO2::SB),
            "SC" => Ok(CountryISO2::SC),
            "SD" => Ok(CountryISO2::SD),
            "SE" => Ok(CountryISO2::SE),
            "SG" => Ok(CountryISO2::SG),
            "SH" => Ok(CountryISO2::SH),
            "SI" => Ok(CountryISO2::SI),
            "SJ" => Ok(CountryISO2::SJ),
            "SK" => Ok(CountryISO2::SK),
            "SL" => Ok(CountryISO2::SL),
            "SM" => Ok(CountryISO2::SM),
            "SN" => Ok(CountryISO2::SN),
            "SO" => Ok(CountryISO2::SO),
            "SR" => Ok(CountryISO2::SR),
            "SS" => Ok(CountryISO2::SS),
            "ST" => Ok(CountryISO2::ST),
            "SV" => Ok(CountryISO2::SV),
            "SX" => Ok(CountryISO2::SX),
            "SY" => Ok(CountryISO2::SY),
            "SZ" => Ok(CountryISO2::SZ),
            "TC" => Ok(CountryISO2::TC),
            "TD" => Ok(CountryISO2::TD),
            "TF" => Ok(CountryISO2::TF),
            "TG" => Ok(CountryISO2::TG),
            "TH" => Ok(CountryISO2::TH),
            "TJ" => Ok(CountryISO2::TJ),
            "TK" => Ok(CountryISO2::TK),
            "TL" => Ok(CountryISO2::TL),
            "TM" => Ok(CountryISO2::TM),
            "TN" => Ok(CountryISO2::TN),
            "TO" => Ok(CountryISO2::TO),
            "TR" => Ok(CountryISO2::TR),
            "TT" => Ok(CountryISO2::TT),
            "TV" => Ok(CountryISO2::TV),
            "TZ" => Ok(CountryISO2::TZ),
            "UA" => Ok(CountryISO2::UA),
            "UG" => Ok(CountryISO2::UG),
            "UM" => Ok(CountryISO2::UM),
            "US" => Ok(CountryISO2::US),
            "UY" => Ok(CountryISO2::UY),
            "UZ" => Ok(CountryISO2::UZ),
            "VA" => Ok(CountryISO2::VA),
            "VC" => Ok(CountryISO2::VC),
            "VE" => Ok(CountryISO2::VE),
            "VG" => Ok(CountryISO2::VG),
            "VI" => Ok(CountryISO2::VI),
            "VN" => Ok(CountryISO2::VN),
            "VU" => Ok(CountryISO2::VU),
            "WF" => Ok(CountryISO2::WF),
            "WS" => Ok(CountryISO2::WS),
            "YE" => Ok(CountryISO2::YE),
            "YT" => Ok(CountryISO2::YT),
            "ZA" => Ok(CountryISO2::ZA),
            "ZM" => Ok(CountryISO2::ZM),
            "ZW" => Ok(CountryISO2::ZW),
            _ => Err(ApiError::ParsingError("Invalid Country ISO2")),
        }
    }
}
