apiVersion: v2
name: decision-engine
description: A Helm chart for the Decision Engine with PostgreSQL and Redis support
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: ~12.5.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mysql
    version: ~13.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: redis
    version: ~17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
