# Use the MySQL image instead of the chart's PostgreSQL default.
image:
  repository: ghcr.io/juspay/decision-engine

decisionEngine:
  useMySQL: true
  usePostgreSQL: false
  useRedis: true

mysql:
  enabled: true
  auth:
    rootPassword: "root"
    database: "jdb"
  primary:
    persistence:
      enabled: true
      size: 8Gi

postgresql:
  enabled: false

dbMigration:
  enabled: true
  postgresql:
    enabled: false
  mysql:
    enabled: true
