use serde::{Deserialize, Serialize};
use std::fmt;
use std::hash::Hash;
use std::option::Option;
use std::string::String;

use crate::error::ApiError;

#[derive(
    Debug, Clone, PartialOrd, Ord, PartialEq, Serialize, Deserialize, Eq, Hash, strum::Display,
)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Gateway {
    Adyen,
    Afterpay,
    Airpay,
    Payphi,
    Airtelmoney,
    Airwallex,
    Amazonpay,
    Amex,
    Amps,
    Atom,
    Authorizedotnet,
    Axis,
    AxisBiz,
    AxisUpi,
    Axisnb,
    Bajajfinserv,
    Bharatx,
    Billdesk,
    Blazepay,
    Braintree,
    Boku,
    Camspay,
    Capillary,
    Capitalfloat,
    Careempay,
    Cash,
    Cashtocode,
    Ccavenue,
    CcavenueV2,
    Checkout,
    Cielo,
    Citi,
    Citrus,
    Cred,
    Cybersource,
    CybsChase,
    Digio,
    DirectBankEmi,
    Dlocal,
    Dummy,
    Earlysalary,
    Easebuzz,
    Ebanx,
    Ebs,
    EbsV3,
    Epaylater,
    Expresspg,
    Facilitatpay,
    FasPay,
    FederalBiz,
    Fdconnect,
    Fib,
    Finbox,
    Flexmoney,
    Flutterwave,
    Freecharge,
    Freechargepg,
    FreechargeV2,
    FssAtmPin,
    FssAtmPinV2,
    Fsspay,
    Gocashfree,
    Gokwik,
    Googlepay,
    GpayImf,
    Gyftr,
    Hdfc,
    HdfcDcEmi,
    HdfcCcEmi,
    HdfcEbsVas,
    HdfcFlexipay,
    HdfcIvr,
    HdfcbankSmartgateway,
    HdfcUpi,
    Hdfcnb,
    Hsbc,
    HsbcUpi,
    Hyperpay,
    Hyperpg,
    HyperPg,
    Iatapay,
    Icici,
    IciciUpi,
    Icicinb,
    Icicipaylater,
    Ifg,
    IndusUpi,
    InspireNetz,
    Instacred,
    IndusPayu,
    Ipg,
    Itau,
    Itzcash,
    Jiomoney,
    Jiopay,
    Kbank,
    Klarna,
    Kotak,
    KotakBiz,
    KotakUpi,
    Lazypay,
    Linepay,
    Loantap,
    Lotuspay,
    Loyltyrewardz,
    Lsp,
    LspEtb,
    Lyra,
    M2p,
    Mercadopago,
    MerchantContainer,
    Midtrans,
    Migs,
    Mobikwik,
    Mobikwikzip,
    Morpheus,
    Mpesa,
    Mpgs,
    Mswipe,
    Myfatoorah,
    Tappay,
    Tazapay,
    Paymob,
    Fawrypay,
    Navitaire,
    Nbbl,
    Mosambee,
    Netcetera,
    Nmi,
    Noon,
    None,
    Nupay,
    Olamoney,
    Olapostpaid,
    Onepay,
    Opnpayments,
    Pagaleve,
    Pagseguo,
    Payamigo,
    Payfort,
    Payglocal,
    Paylater,
    Paypal,
    Paytm,
    PaytmUpi,
    PaytmV2,
    Payu,
    Payzapp,
    Phonepe,
    Pinelabs,
    PinelabsOffline,
    Postpay,
    Qwikcilver,
    Razorpay,
    Rbl,
    RblBiz,
    Sbi,
    SbiUpi,
    Sbibuddy,
    Sbiepay,
    Sezzle,
    Shopse,
    SikaSimpl,
    Simpl,
    Snapmint,
    Sodexo,
    Stripe,
    Tabby,
    TataPa,
    TataUpi,
    Tatanue,
    Tatapay,
    Tatapaylater,
    Tap,
    Tpsl,
    TpslSi,
    Triplea,
    Trustpay,
    Twid,
    TwidV2,
    TwocTwop,
    VijayaUpi,
    Volt,
    VisaPbw,
    WalletContainer,
    Worldpay,
    Xendit,
    YesBiz,
    YesbankUpi,
    Ypp,
    Zaakpay,
    Zestmoney,
    Doku,
    Zaincash,
    Fastpay,
    Pay10,
    PinelabsOnline,
    Wibmo,
    Ndps,
    Default,
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum GatewayAny {
    GatewayKnown(Gateway),
    GatewayUnknown,
}

impl fmt::Display for GatewayAny {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match gateway_any_to_text(self) {
            Some(text) => write!(f, "{}", text),
            None => write!(f, "UnknownGateway"),
        }
    }
}

pub fn gateway_any_to_text(gateway_any: &GatewayAny) -> Option<String> {
    match gateway_any {
        GatewayAny::GatewayKnown(gateway) => Some(gateway.to_string()),
        GatewayAny::GatewayUnknown => None,
    }
}

pub fn text_to_gateway(text: &str) -> Result<Gateway, ApiError> {
    match text {
        "ADYEN" => Ok(Gateway::Adyen),
        "AFTERPAY" => Ok(Gateway::Afterpay),
        "AIRPAY" => Ok(Gateway::Airpay),
        "PAYPHI" => Ok(Gateway::Payphi),
        "AIRTELMONEY" => Ok(Gateway::Airtelmoney),
        "AIRWALLEX" => Ok(Gateway::Airwallex),
        "AMAZONPAY" => Ok(Gateway::Amazonpay),
        "AMEX" => Ok(Gateway::Amex),
        "AMPS" => Ok(Gateway::Amps),
        "ATOM" => Ok(Gateway::Atom),
        "AUTHORIZEDOTNET" => Ok(Gateway::Authorizedotnet),
        "AXIS_BIZ" => Ok(Gateway::AxisBiz),
        "AXIS_UPI" => Ok(Gateway::AxisUpi),
        "AXIS" => Ok(Gateway::Axis),
        "AXISNB" => Ok(Gateway::Axisnb),
        "BAJAJFINSERV" => Ok(Gateway::Bajajfinserv),
        "BHARATX" => Ok(Gateway::Bharatx),
        "BILLDESK" => Ok(Gateway::Billdesk),
        "BLAZEPAY" => Ok(Gateway::Blazepay),
        "BRAINTREE" => Ok(Gateway::Braintree),
        "BOKU" => Ok(Gateway::Boku),
        "CAMSPAY" => Ok(Gateway::Camspay),
        "CAPILLARY" => Ok(Gateway::Capillary),
        "CAPITALFLOAT" => Ok(Gateway::Capitalfloat),
        "CAREEMPAY" => Ok(Gateway::Careempay),
        "CASH" => Ok(Gateway::Cash),
        "CASHTOCODE" => Ok(Gateway::Cashtocode),
        "CCAVENUE_V2" => Ok(Gateway::CcavenueV2),
        "CCAVENUE" => Ok(Gateway::Ccavenue),
        "CHECKOUT" => Ok(Gateway::Checkout),
        "CIELO" => Ok(Gateway::Cielo),
        "CITI" => Ok(Gateway::Citi),
        "CITRUS" => Ok(Gateway::Citrus),
        "CRED" => Ok(Gateway::Cred),
        "CYBERSOURCE" => Ok(Gateway::Cybersource),
        "CYBS_CHASE" => Ok(Gateway::CybsChase),
        "DIGIO" => Ok(Gateway::Digio),
        "DLOCAL" => Ok(Gateway::Dlocal),
        "DUMMY" => Ok(Gateway::Dummy),
        "EARLYSALARY" => Ok(Gateway::Earlysalary),
        "EASEBUZZ" => Ok(Gateway::Easebuzz),
        "EBANX" => Ok(Gateway::Ebanx),
        "EBS_V3" => Ok(Gateway::EbsV3),
        "EBS" => Ok(Gateway::Ebs),
        "EPAYLATER" => Ok(Gateway::Epaylater),
        "EXPRESSPG" => Ok(Gateway::Expresspg),
        "FACILITAPAY" => Ok(Gateway::Facilitatpay),
        "FASPAY" => Ok(Gateway::FasPay),
        "FASTPAY" => Ok(Gateway::Fastpay),
        "FEDERAL_BIZ" => Ok(Gateway::FederalBiz),
        "FDCONNECT" => Ok(Gateway::Fdconnect),
        "FIB" => Ok(Gateway::Fib),
        "FINBOX" => Ok(Gateway::Finbox),
        "FLEXMONEY" => Ok(Gateway::Flexmoney),
        "FLUTTERWAVE" => Ok(Gateway::Flutterwave),
        "FREECHARGE_V2" => Ok(Gateway::FreechargeV2),
        "FREECHARGEPG" => Ok(Gateway::Freechargepg),
        "FREECHARGE" => Ok(Gateway::Freecharge),
        "FSS_ATM_PIN_V2" => Ok(Gateway::FssAtmPinV2),
        "FSS_ATM_PIN" => Ok(Gateway::FssAtmPin),
        "FSSPAY" => Ok(Gateway::Fsspay),
        "GOCASHFREE" => Ok(Gateway::Gocashfree),
        "GOKWIK" => Ok(Gateway::Gokwik),
        "GOOGLEPAY" => Ok(Gateway::Googlepay),
        "GPAY_IMF" => Ok(Gateway::GpayImf),
        "GYFTR" => Ok(Gateway::Gyftr),
        "HDFC_DC_EMI" => Ok(Gateway::HdfcDcEmi),
        "HDFC_CC_EMI" => Ok(Gateway::HdfcCcEmi),
        "HDFC_EBS_VAS" => Ok(Gateway::HdfcEbsVas),
        "HDFC_FLEXIPAY" => Ok(Gateway::HdfcFlexipay),
        "HDFC_IVR" => Ok(Gateway::HdfcIvr),
        "HDFCBANK_SMARTGATEWAY" => Ok(Gateway::HdfcbankSmartgateway),
        "HDFC_UPI" => Ok(Gateway::HdfcUpi),
        "HDFC" => Ok(Gateway::Hdfc),
        "HDFCNB" => Ok(Gateway::Hdfcnb),
        "HSBC" => Ok(Gateway::Hsbc),
        "HSBC_UPI" => Ok(Gateway::HsbcUpi),
        "HYPERPG" => Ok(Gateway::Hyperpg),
        "HYPERPAY" => Ok(Gateway::Hyperpay),
        "HYPER_PG" => Ok(Gateway::HyperPg),
        "IATAPAY" => Ok(Gateway::Iatapay),
        "ICICI_UPI" => Ok(Gateway::IciciUpi),
        "ICICI" => Ok(Gateway::Icici),
        "ICICINB" => Ok(Gateway::Icicinb),
        "ICICIPAYLATER" => Ok(Gateway::Icicipaylater),
        "IFG" => Ok(Gateway::Ifg),
        "INDUS_UPI" => Ok(Gateway::IndusUpi),
        "INSPIRE_NETZ" => Ok(Gateway::InspireNetz),
        "INSTACRED" => Ok(Gateway::Instacred),
        "INDUS_PAYU" => Ok(Gateway::IndusPayu),
        "IPG" => Ok(Gateway::Ipg),
        "ITAU" => Ok(Gateway::Itau),
        "ITZCASH" => Ok(Gateway::Itzcash),
        "JIOMONEY" => Ok(Gateway::Jiomoney),
        "JIOPAY" => Ok(Gateway::Jiopay),
        "KBANK" => Ok(Gateway::Kbank),
        "KLARNA" => Ok(Gateway::Klarna),
        "KOTAK_UPI" => Ok(Gateway::KotakUpi),
        "KOTAK" => Ok(Gateway::Kotak),
        "KOTAK_BIZ" => Ok(Gateway::KotakBiz),
        "LAZYPAY" => Ok(Gateway::Lazypay),
        "LINEPAY" => Ok(Gateway::Linepay),
        "LOANTAP" => Ok(Gateway::Loantap),
        "LOTUSPAY" => Ok(Gateway::Lotuspay),
        "LOYLTYREWARDZ" => Ok(Gateway::Loyltyrewardz),
        "LSP" => Ok(Gateway::Lsp),
        "LSP_ETB" => Ok(Gateway::LspEtb),
        "LYRA" => Ok(Gateway::Lyra),
        "M2P" => Ok(Gateway::M2p),
        "MERCADOPAGO" => Ok(Gateway::Mercadopago),
        "MERCHANT_CONTAINER" => Ok(Gateway::MerchantContainer),
        "MIDTRANS" => Ok(Gateway::Midtrans),
        "MIGS" => Ok(Gateway::Migs),
        "MOBIKWIK" => Ok(Gateway::Mobikwik),
        "MOBIKWIKZIP" => Ok(Gateway::Mobikwikzip),
        "MORPHEUS" => Ok(Gateway::Morpheus),
        "MPESA" => Ok(Gateway::Mpesa),
        "MPGS" => Ok(Gateway::Mpgs),
        "MSWIPE" => Ok(Gateway::Mswipe),
        "MYFATOORAH" => Ok(Gateway::Myfatoorah),
        "TAPPAY" => Ok(Gateway::Tappay),
        "TAZAPAY" => Ok(Gateway::Tazapay),
        "PAYMOB" => Ok(Gateway::Paymob),
        "FAWRYPAY" => Ok(Gateway::Fawrypay),
        "NAVITAIRE" => Ok(Gateway::Navitaire),
        "NBBL" => Ok(Gateway::Nbbl),
        "MOSAMBEE" => Ok(Gateway::Mosambee),
        "NETCETERA" => Ok(Gateway::Netcetera),
        "NMI" => Ok(Gateway::Nmi),
        "NOON" => Ok(Gateway::Noon),
        "NONE" => Ok(Gateway::None),
        "NUPAY" => Ok(Gateway::Nupay),
        "OLAMONEY" => Ok(Gateway::Olamoney),
        "OLAPOSTPAID" => Ok(Gateway::Olapostpaid),
        "ONEPAY" => Ok(Gateway::Onepay),
        "OPNPAYMENTS" => Ok(Gateway::Opnpayments),
        "PAGALEVE" => Ok(Gateway::Pagaleve),
        "PAGSEGURO" => Ok(Gateway::Pagseguo),
        "PAYAMIGO" => Ok(Gateway::Payamigo),
        "PAYFORT" => Ok(Gateway::Payfort),
        "PAYGLOCAL" => Ok(Gateway::Payglocal),
        "PAYLATER" => Ok(Gateway::Paylater),
        "PAYPAL" => Ok(Gateway::Paypal),
        "PAYTM_UPI" => Ok(Gateway::PaytmUpi),
        "PAYTM_V2" => Ok(Gateway::PaytmV2),
        "PAYTM" => Ok(Gateway::Paytm),
        "PAYU" => Ok(Gateway::Payu),
        "PAYZAPP" => Ok(Gateway::Payzapp),
        "PHONEPE" => Ok(Gateway::Phonepe),
        "PINELABS" => Ok(Gateway::Pinelabs),
        "PINELABS_OFFLINE" => Ok(Gateway::PinelabsOffline),
        "POSTPAY" => Ok(Gateway::Postpay),
        "QWIKCILVER" => Ok(Gateway::Qwikcilver),
        "RAZORPAY" => Ok(Gateway::Razorpay),
        "RBL_BIZ" => Ok(Gateway::RblBiz),
        "RBL" => Ok(Gateway::Rbl),
        "SBI_UPI" => Ok(Gateway::SbiUpi),
        "SBI" => Ok(Gateway::Sbi),
        "SBIBUDDY" => Ok(Gateway::Sbibuddy),
        "SBIePAY" => Ok(Gateway::Sbiepay),
        "SEZZLE" => Ok(Gateway::Sezzle),
        "SHOPSE" => Ok(Gateway::Shopse),
        "SIKA_SIMPL" => Ok(Gateway::SikaSimpl),
        "SIMPL" => Ok(Gateway::Simpl),
        "SNAPMINT" => Ok(Gateway::Snapmint),
        "SODEXO" => Ok(Gateway::Sodexo),
        "STRIPE" => Ok(Gateway::Stripe),
        "TABBY" => Ok(Gateway::Tabby),
        "TATA_PA" => Ok(Gateway::TataPa),
        "TATA_UPI" => Ok(Gateway::TataUpi),
        "TATANEU" => Ok(Gateway::Tatanue),
        "TATAPAY" => Ok(Gateway::Tatapay),
        "TATAPAYLATER" => Ok(Gateway::Tatapaylater),
        "TAP" => Ok(Gateway::Tap),
        "TPSL_SI" => Ok(Gateway::TpslSi),
        "TPSL" => Ok(Gateway::Tpsl),
        "TRIPLEA" => Ok(Gateway::Triplea),
        "TRUSTPAY" => Ok(Gateway::Trustpay),
        "TWID" => Ok(Gateway::Twid),
        "TWID_V2" => Ok(Gateway::TwidV2),
        "TWOC_TWOP" => Ok(Gateway::TwocTwop),
        "VIJAYA_UPI" => Ok(Gateway::VijayaUpi),
        "VISA_PBW" => Ok(Gateway::VisaPbw),
        "VOLT" => Ok(Gateway::Volt),
        "WALLET_CONTAINER" => Ok(Gateway::WalletContainer),
        "WORLDPAY" => Ok(Gateway::Worldpay),
        "XENDIT" => Ok(Gateway::Xendit),
        "YES_BIZ" => Ok(Gateway::YesBiz),
        "YESBANK_UPI" => Ok(Gateway::YesbankUpi),
        "YPP" => Ok(Gateway::Ypp),
        "ZAAKPAY" => Ok(Gateway::Zaakpay),
        "ZESTMONEY" => Ok(Gateway::Zestmoney),
        "DOKU" => Ok(Gateway::Doku),
        "DIRECT_BANK_EMI" => Ok(Gateway::DirectBankEmi),
        "ZAINCASH" => Ok(Gateway::Zaincash),
        "PAY10" => Ok(Gateway::Pay10),
        "PINELABS_ONLINE" => Ok(Gateway::PinelabsOnline),
        "WIBMO" => Ok(Gateway::Wibmo),
        "NDPS" => Ok(Gateway::Ndps),
        "DEFAULT" => Ok(Gateway::Default),
        _ => Err(ApiError::ParsingError("Invalid Gateway")),
    }
}
