use serde::{Deserialize, Serialize};
use std::fmt;
use std::hash::Hash;
use std::option::Option;
use std::string::String;

use crate::error::ApiError;

#[derive(
    Debug, Clone, PartialOrd, Ord, PartialEq, Serialize, Deserialize, Eq, Hash, strum::Display,
)]
pub enum Gateway {
    ADYEN,
    AFTERPAY,
    AIRPAY,
    PAYPHI,
    AIRTELMONEY,
    AIRWALLEX,
    AMAZONPAY,
    AMEX,
    AMPS,
    ATOM,
    AUTHORIZEDOTNET,
    AXIS,
    AxisBiz,
    AxisUpi,
    AXISNB,
    BAJAJFINSERV,
    BHARATX,
    BILLDESK,
    BLAZEPAY,
    BRAINTREE,
    BOKU,
    CAMSPAY,
    CAPILLARY,
    CAPITALFLOAT,
    CAREEMPAY,
    CASH,
    CASHTOCODE,
    CCAVENUE,
    CcavenueV2,
    CHECKOUT,
    CIELO,
    CITI,
    CITRUS,
    CRED,
    CYBERSOURCE,
    CybsChase,
    DIGIO,
    DirectBankEmi,
    DLOCAL,
    DUMMY,
    EARLYSALARY,
    EASEBUZZ,
    EBANX,
    EBS,
    EbsV3,
    EPAYLATER,
    EXPRESSPG,
    FACILITAPAY,
    FASPAY,
    FederalBiz,
    FDCONNECT,
    FIB,
    FINBOX,
    FLEXMONEY,
    FLUTTERWAVE,
    FREECHARGE,
    FREECHARGEPG,
    FreechargeV2,
    FssAtmPin,
    FssAtmPinV2,
    FSSPAY,
    GOCASHFREE,
    GOKWIK,
    GOOGLEPAY,
    GpayImf,
    GYFTR,
    HDFC,
    HdfcDcEmi,
    HdfcCcEmi,
    HdfcEbsVas,
    HdfcFlexipay,
    HdfcIvr,
    HdfcbankSmartgateway,
    HdfcUpi,
    HDFCNB,
    HSBC,
    HsbcUpi,
    HYPERPAY,
    HYPERPG,
    HyperPg,
    IATAPAY,
    ICICI,
    IciciUpi,
    ICICINB,
    ICICIPAYLATER,
    IFG,
    IndusUpi,
    InspireNetz,
    INSTACRED,
    IndusPayu,
    IPG,
    ITAU,
    ITZCASH,
    JIOMONEY,
    JIOPAY,
    KBANK,
    KLARNA,
    KOTAK,
    KotakBiz,
    KotakUpi,
    LAZYPAY,
    LINEPAY,
    LOANTAP,
    LOTUSPAY,
    LOYLTYREWARDZ,
    LSP,
    LspEtb,
    LYRA,
    M2P,
    MERCADOPAGO,
    MerchantContainer,
    MIDTRANS,
    MIGS,
    MOBIKWIK,
    MOBIKWIKZIP,
    MORPHEUS,
    MPESA,
    MPGS,
    MSWIPE,
    MYFATOORAH,
    TAPPAY,
    TAZAPAY,
    PAYMOB,
    FAWRYPAY,
    NAVITAIRE,
    NBBL,
    MOSAMBEE,
    NETCETERA,
    NMI,
    NOON,
    NONE,
    NUPAY,
    OLAMONEY,
    OLAPOSTPAID,
    ONEPAY,
    OPNPAYMENTS,
    PAGALEVE,
    PAGSEGURO,
    PAYAMIGO,
    PAYFORT,
    PAYGLOCAL,
    PAYLATER,
    PAYPAL,
    PAYTM,
    PaytmUpi,
    PaytmV2,
    PAYU,
    PAYZAPP,
    PHONEPE,
    PINELABS,
    PinelabsOffline,
    POSTPAY,
    QWIKCILVER,
    RAZORPAY,
    RBL,
    RblBiz,
    SBI,
    SbiUpi,
    SBIBUDDY,
    SBIePAY,
    SEZZLE,
    SHOPSE,
    SikaSimpl,
    SIMPL,
    SNAPMINT,
    SODEXO,
    STRIPE,
    TABBY,
    TataPa,
    TataUpi,
    TATANEU,
    TATAPAY,
    TATAPAYLATER,
    TAP,
    TPSL,
    TpslSi,
    TRIPLEA,
    TRUSTPAY,
    TWID,
    TwidV2,
    TwocTwop,
    VijayaUpi,
    VOLT,
    VisaPbw,
    WalletContainer,
    WORLDPAY,
    XENDIT,
    YesBiz,
    YesbankUpi,
    YPP,
    ZAAKPAY,
    ZESTMONEY,
    DOKU,
    ZAINCASH,
    FASTPAY,
    PAY10,
    PinelabsOnline,
    WIBMO,
    NDPS,
    DEFAULT,
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum GatewayAny {
    GatewayKnown(Gateway),
    GatewayUnknown,
}

impl fmt::Display for GatewayAny {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match gateway_any_to_text(self) {
            Some(text) => write!(f, "{}", text),
            None => write!(f, "UnknownGateway"),
        }
    }
}

pub fn gateway_any_to_text(gateway_any: &GatewayAny) -> Option<String> {
    match gateway_any {
        GatewayAny::GatewayKnown(gateway) => Some(gateway.to_string()),
        GatewayAny::GatewayUnknown => None,
    }
}

pub fn text_to_gateway(text: &str) -> Result<Gateway, ApiError> {
    match text {
        "ADYEN" => Ok(Gateway::ADYEN),
        "AFTERPAY" => Ok(Gateway::AFTERPAY),
        "AIRPAY" => Ok(Gateway::AIRPAY),
        "PAYPHI" => Ok(Gateway::PAYPHI),
        "AIRTELMONEY" => Ok(Gateway::AIRTELMONEY),
        "AIRWALLEX" => Ok(Gateway::AIRWALLEX),
        "AMAZONPAY" => Ok(Gateway::AMAZONPAY),
        "AMEX" => Ok(Gateway::AMEX),
        "AMPS" => Ok(Gateway::AMPS),
        "ATOM" => Ok(Gateway::ATOM),
        "AUTHORIZEDOTNET" => Ok(Gateway::AUTHORIZEDOTNET),
        "AXIS_BIZ" => Ok(Gateway::AxisBiz),
        "AXIS_UPI" => Ok(Gateway::AxisUpi),
        "AXIS" => Ok(Gateway::AXIS),
        "AXISNB" => Ok(Gateway::AXISNB),
        "BAJAJFINSERV" => Ok(Gateway::BAJAJFINSERV),
        "BHARATX" => Ok(Gateway::BHARATX),
        "BILLDESK" => Ok(Gateway::BILLDESK),
        "BLAZEPAY" => Ok(Gateway::BLAZEPAY),
        "BRAINTREE" => Ok(Gateway::BRAINTREE),
        "BOKU" => Ok(Gateway::BOKU),
        "CAMSPAY" => Ok(Gateway::CAMSPAY),
        "CAPILLARY" => Ok(Gateway::CAPILLARY),
        "CAPITALFLOAT" => Ok(Gateway::CAPITALFLOAT),
        "CAREEMPAY" => Ok(Gateway::CAREEMPAY),
        "CASH" => Ok(Gateway::CASH),
        "CASHTOCODE" => Ok(Gateway::CASHTOCODE),
        "CCAVENUE_V2" => Ok(Gateway::CcavenueV2),
        "CCAVENUE" => Ok(Gateway::CCAVENUE),
        "CHECKOUT" => Ok(Gateway::CHECKOUT),
        "CIELO" => Ok(Gateway::CIELO),
        "CITI" => Ok(Gateway::CITI),
        "CITRUS" => Ok(Gateway::CITRUS),
        "CRED" => Ok(Gateway::CRED),
        "CYBERSOURCE" => Ok(Gateway::CYBERSOURCE),
        "CYBS_CHASE" => Ok(Gateway::CybsChase),
        "DIGIO" => Ok(Gateway::DIGIO),
        "DLOCAL" => Ok(Gateway::DLOCAL),
        "DUMMY" => Ok(Gateway::DUMMY),
        "EARLYSALARY" => Ok(Gateway::EARLYSALARY),
        "EASEBUZZ" => Ok(Gateway::EASEBUZZ),
        "EBANX" => Ok(Gateway::EBANX),
        "EBS_V3" => Ok(Gateway::EbsV3),
        "EBS" => Ok(Gateway::EBS),
        "EPAYLATER" => Ok(Gateway::EPAYLATER),
        "EXPRESSPG" => Ok(Gateway::EXPRESSPG),
        "FACILITAPAY" => Ok(Gateway::FACILITAPAY),
        "FASPAY" => Ok(Gateway::FASPAY),
        "FASTPAY" => Ok(Gateway::FASTPAY),
        "FEDERAL_BIZ" => Ok(Gateway::FederalBiz),
        "FDCONNECT" => Ok(Gateway::FDCONNECT),
        "FIB" => Ok(Gateway::FIB),
        "FINBOX" => Ok(Gateway::FINBOX),
        "FLEXMONEY" => Ok(Gateway::FLEXMONEY),
        "FLUTTERWAVE" => Ok(Gateway::FLUTTERWAVE),
        "FREECHARGE_V2" => Ok(Gateway::FreechargeV2),
        "FREECHARGEPG" => Ok(Gateway::FREECHARGEPG),
        "FREECHARGE" => Ok(Gateway::FREECHARGE),
        "FSS_ATM_PIN_V2" => Ok(Gateway::FssAtmPinV2),
        "FSS_ATM_PIN" => Ok(Gateway::FssAtmPin),
        "FSSPAY" => Ok(Gateway::FSSPAY),
        "GOCASHFREE" => Ok(Gateway::GOCASHFREE),
        "GOKWIK" => Ok(Gateway::GOKWIK),
        "GOOGLEPAY" => Ok(Gateway::GOOGLEPAY),
        "GPAY_IMF" => Ok(Gateway::GpayImf),
        "GYFTR" => Ok(Gateway::GYFTR),
        "HDFC_DC_EMI" => Ok(Gateway::HdfcDcEmi),
        "HDFC_CC_EMI" => Ok(Gateway::HdfcCcEmi),
        "HDFC_EBS_VAS" => Ok(Gateway::HdfcEbsVas),
        "HDFC_FLEXIPAY" => Ok(Gateway::HdfcFlexipay),
        "HDFC_IVR" => Ok(Gateway::HdfcIvr),
        "HDFCBANK_SMARTGATEWAY" => Ok(Gateway::HdfcbankSmartgateway),
        "HDFC_UPI" => Ok(Gateway::HdfcUpi),
        "HDFC" => Ok(Gateway::HDFC),
        "HDFCNB" => Ok(Gateway::HDFCNB),
        "HSBC" => Ok(Gateway::HSBC),
        "HSBC_UPI" => Ok(Gateway::HsbcUpi),
        "HYPERPG" => Ok(Gateway::HYPERPG),
        "HYPERPAY" => Ok(Gateway::HYPERPAY),
        "HYPER_PG" => Ok(Gateway::HyperPg),
        "IATAPAY" => Ok(Gateway::IATAPAY),
        "ICICI_UPI" => Ok(Gateway::IciciUpi),
        "ICICI" => Ok(Gateway::ICICI),
        "ICICINB" => Ok(Gateway::ICICINB),
        "ICICIPAYLATER" => Ok(Gateway::ICICIPAYLATER),
        "IFG" => Ok(Gateway::IFG),
        "INDUS_UPI" => Ok(Gateway::IndusUpi),
        "INSPIRE_NETZ" => Ok(Gateway::InspireNetz),
        "INSTACRED" => Ok(Gateway::INSTACRED),
        "INDUS_PAYU" => Ok(Gateway::IndusPayu),
        "IPG" => Ok(Gateway::IPG),
        "ITAU" => Ok(Gateway::ITAU),
        "ITZCASH" => Ok(Gateway::ITZCASH),
        "JIOMONEY" => Ok(Gateway::JIOMONEY),
        "JIOPAY" => Ok(Gateway::JIOPAY),
        "KBANK" => Ok(Gateway::KBANK),
        "KLARNA" => Ok(Gateway::KLARNA),
        "KOTAK_UPI" => Ok(Gateway::KotakUpi),
        "KOTAK" => Ok(Gateway::KOTAK),
        "KOTAK_BIZ" => Ok(Gateway::KotakBiz),
        "LAZYPAY" => Ok(Gateway::LAZYPAY),
        "LINEPAY" => Ok(Gateway::LINEPAY),
        "LOANTAP" => Ok(Gateway::LOANTAP),
        "LOTUSPAY" => Ok(Gateway::LOTUSPAY),
        "LOYLTYREWARDZ" => Ok(Gateway::LOYLTYREWARDZ),
        "LSP" => Ok(Gateway::LSP),
        "LSP_ETB" => Ok(Gateway::LspEtb),
        "LYRA" => Ok(Gateway::LYRA),
        "M2P" => Ok(Gateway::M2P),
        "MERCADOPAGO" => Ok(Gateway::MERCADOPAGO),
        "MERCHANT_CONTAINER" => Ok(Gateway::MerchantContainer),
        "MIDTRANS" => Ok(Gateway::MIDTRANS),
        "MIGS" => Ok(Gateway::MIGS),
        "MOBIKWIK" => Ok(Gateway::MOBIKWIK),
        "MOBIKWIKZIP" => Ok(Gateway::MOBIKWIKZIP),
        "MORPHEUS" => Ok(Gateway::MORPHEUS),
        "MPESA" => Ok(Gateway::MPESA),
        "MPGS" => Ok(Gateway::MPGS),
        "MSWIPE" => Ok(Gateway::MSWIPE),
        "MYFATOORAH" => Ok(Gateway::MYFATOORAH),
        "TAPPAY" => Ok(Gateway::TAPPAY),
        "TAZAPAY" => Ok(Gateway::TAZAPAY),
        "PAYMOB" => Ok(Gateway::PAYMOB),
        "FAWRYPAY" => Ok(Gateway::FAWRYPAY),
        "NAVITAIRE" => Ok(Gateway::NAVITAIRE),
        "NBBL" => Ok(Gateway::NBBL),
        "MOSAMBEE" => Ok(Gateway::MOSAMBEE),
        "NETCETERA" => Ok(Gateway::NETCETERA),
        "NMI" => Ok(Gateway::NMI),
        "NOON" => Ok(Gateway::NOON),
        "NONE" => Ok(Gateway::NONE),
        "NUPAY" => Ok(Gateway::NUPAY),
        "OLAMONEY" => Ok(Gateway::OLAMONEY),
        "OLAPOSTPAID" => Ok(Gateway::OLAPOSTPAID),
        "ONEPAY" => Ok(Gateway::ONEPAY),
        "OPNPAYMENTS" => Ok(Gateway::OPNPAYMENTS),
        "PAGALEVE" => Ok(Gateway::PAGALEVE),
        "PAGSEGURO" => Ok(Gateway::PAGSEGURO),
        "PAYAMIGO" => Ok(Gateway::PAYAMIGO),
        "PAYFORT" => Ok(Gateway::PAYFORT),
        "PAYGLOCAL" => Ok(Gateway::PAYGLOCAL),
        "PAYLATER" => Ok(Gateway::PAYLATER),
        "PAYPAL" => Ok(Gateway::PAYPAL),
        "PAYTM_UPI" => Ok(Gateway::PaytmUpi),
        "PAYTM_V2" => Ok(Gateway::PaytmV2),
        "PAYTM" => Ok(Gateway::PAYTM),
        "PAYU" => Ok(Gateway::PAYU),
        "PAYZAPP" => Ok(Gateway::PAYZAPP),
        "PHONEPE" => Ok(Gateway::PHONEPE),
        "PINELABS" => Ok(Gateway::PINELABS),
        "PINELABS_OFFLINE" => Ok(Gateway::PinelabsOffline),
        "POSTPAY" => Ok(Gateway::POSTPAY),
        "QWIKCILVER" => Ok(Gateway::QWIKCILVER),
        "RAZORPAY" => Ok(Gateway::RAZORPAY),
        "RBL_BIZ" => Ok(Gateway::RblBiz),
        "RBL" => Ok(Gateway::RBL),
        "SBI_UPI" => Ok(Gateway::SbiUpi),
        "SBI" => Ok(Gateway::SBI),
        "SBIBUDDY" => Ok(Gateway::SBIBUDDY),
        "SBIePAY" => Ok(Gateway::SBIePAY),
        "SEZZLE" => Ok(Gateway::SEZZLE),
        "SHOPSE" => Ok(Gateway::SHOPSE),
        "SIKA_SIMPL" => Ok(Gateway::SikaSimpl),
        "SIMPL" => Ok(Gateway::SIMPL),
        "SNAPMINT" => Ok(Gateway::SNAPMINT),
        "SODEXO" => Ok(Gateway::SODEXO),
        "STRIPE" => Ok(Gateway::STRIPE),
        "TABBY" => Ok(Gateway::TABBY),
        "TATA_PA" => Ok(Gateway::TataPa),
        "TATA_UPI" => Ok(Gateway::TataUpi),
        "TATANEU" => Ok(Gateway::TATANEU),
        "TATAPAY" => Ok(Gateway::TATAPAY),
        "TATAPAYLATER" => Ok(Gateway::TATAPAYLATER),
        "TAP" => Ok(Gateway::TAP),
        "TPSL_SI" => Ok(Gateway::TpslSi),
        "TPSL" => Ok(Gateway::TPSL),
        "TRIPLEA" => Ok(Gateway::TRIPLEA),
        "TRUSTPAY" => Ok(Gateway::TRUSTPAY),
        "TWID" => Ok(Gateway::TWID),
        "TWID_V2" => Ok(Gateway::TwidV2),
        "TWOC_TWOP" => Ok(Gateway::TwocTwop),
        "VIJAYA_UPI" => Ok(Gateway::VijayaUpi),
        "VISA_PBW" => Ok(Gateway::VisaPbw),
        "VOLT" => Ok(Gateway::VOLT),
        "WALLET_CONTAINER" => Ok(Gateway::WalletContainer),
        "WORLDPAY" => Ok(Gateway::WORLDPAY),
        "XENDIT" => Ok(Gateway::XENDIT),
        "YES_BIZ" => Ok(Gateway::YesBiz),
        "YESBANK_UPI" => Ok(Gateway::YesbankUpi),
        "YPP" => Ok(Gateway::YPP),
        "ZAAKPAY" => Ok(Gateway::ZAAKPAY),
        "ZESTMONEY" => Ok(Gateway::ZESTMONEY),
        "DOKU" => Ok(Gateway::DOKU),
        "DIRECT_BANK_EMI" => Ok(Gateway::DirectBankEmi),
        "ZAINCASH" => Ok(Gateway::ZAINCASH),
        "PAY10" => Ok(Gateway::PAY10),
        "PINELABS_ONLINE" => Ok(Gateway::PinelabsOnline),
        "WIBMO" => Ok(Gateway::WIBMO),
        "NDPS" => Ok(Gateway::NDPS),
        "DEFAULT" => Ok(Gateway::DEFAULT),
        _ => Err(ApiError::ParsingError("Invalid Gateway")),
    }
}
