CREATE TABLE analytics_domain_events (
    event_id UInt64,
    api_flow LowCardinality(String),
    flow_type LowCardinality(String),
    merchant_id Nullable(String),
    merchant_id_key String MATERIALIZED ifNull(merchant_id, ''),
    payment_id Nullable(String),
    payment_id_key String MATERIALIZED ifNull(payment_id, ''),
    request_id Nullable(String),
    request_id_key String MATERIALIZED ifNull(request_id, ''),
    global_request_id Nullable(String),
    trace_id Nullable(String),
    payment_method_type Nullable(String),
    payment_method Nullable(String),
    card_network Nullable(String),
    card_is_in Nullable(String),
    currency Nullable(String),
    country Nullable(String),
    auth_type Nullable(String),
    gateway Nullable(String),
    event_stage Nullable(String),
    routing_approach Nullable(String),
    rule_name Nullable(String),
    status Nullable(String),
    error_code Nullable(String),
    error_message Nullable(String),
    score_value Nullable(Float64),
    sigma_factor Nullable(Float64),
    average_latency Nullable(Float64),
    tp99_latency Nullable(Float64),
    transaction_count Nullable(Int64),
    route Nullable(String),
    details Nullable(String),
    created_at_ms Int64,
    created_at DateTime64(3, 'UTC') MATERIALIZED fromUnixTimestamp64Milli(created_at_ms)
) ENGINE = ReplacingMergeTree(event_id)
PARTITION BY toYYYYMM(created_at)
ORDER BY (
    merchant_id_key,
    created_at_ms,
    api_flow,
    flow_type,
    request_id_key,
    payment_id_key,
    event_id
)
TTL created_at + INTERVAL 18 MONTH;
