{{- if .Values.groovyRunner.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "decision-engine.groovyRunnerName" . }}
  labels:
    {{- include "decision-engine.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.groovyRunner.metadata.labels.component }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.groovyRunner.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "decision-engine.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.groovyRunner.metadata.labels.component }}
{{- end }}
